name: testLab
channels:
  - defaults
dependencies:
  - python>=3.6
  - imageio
  - jupyter 
  - matplotlib
  - numpy
  - pandas
  - scipy
  - tqdm
  - xlwt
  - xlrd
  - pip:
    - mpld3
    - os
    - skimage
    - sys

